### ISSUE TITLE
apparently the driver does not return errors to the pipeline driver

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/worker#4]
i run the eval with the next function:
	"(input,require)=> {",
					"const result= input[0][0]+input[0][1]",
					"result=100;",
					"return result;}"

as you can see i try to give a value to a const.
the node result is ""ERROR TypeError: Assignment to constant variable"
but the pipeline status is completed.
should be failed.

**Comment by yehiyam** [comment]
already fixed
